=== sachinaralapura/portfolio/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "fontFamily": {
      "type": "string"
    },
    "navList": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "about": {
      "type": "object",
      "properties": {
        "fname": {
          "type": "string"
        },
        "lname": {
          "type": "string"
        },
        "occ": {
          "type": "string"
        },
        "primary": {
          "type": "string"
        },
        "secondary": {
          "type": "string"
        }
      },
      "required": ["fname", "lname", "occ", "primary", "secondary"]
    },
    "skills": {
      "type": "object",
      "properties": {
        "skillList": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "image": {
                  "type": "string"
                },
                "exp": {
                  "type": "integer"
                },
                "add": {
                  "type": "boolean"
                }
              },
              "required": ["name", "image", "exp", "add"]
            }
          ]
        }
      },
      "required": ["skillList"]
    },
    "projects": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "image": {
              "type": "string"
            },
            "link": {
              "type": "string"
            },
            "githublink": {
              "type": "string"
            }
          },
          "required": ["name", "description", "image", "link", "githublink", "skills"]
        }
      ]
    },
    "contact": {
      "type": "object",
      "properties": {
        "emailJs": {
          "type": "object",
          "properties": {
            "gmailId": {
              "type": "string"
            },
            "serviceId": {
              "type": "string"
            },
            "templateId": {
              "type": "string"
            },
            "publicAPI": {
              "type": "string"
            }
          },
          "required": ["serviceId", "templateId", "publicAPI"]
        },
        "social": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "platform": {
                  "type": "string"
                },
                "link": {
                  "type": "string"
                },
                "img": {
                  "type": "string"
                },
                "add": {
                  "type": "boolean"
                }
              },
              "required": ["platform", "link", "img", "add"]
            }
          ]
        }
      },
      "required": ["emailJs", "social"]
    }
  },
  "required": ["navList", "about", "skills", "projects", "contact"]
}

=== sachinaralapura/portfolio/src/data.json
{
  "fontFamily": "monospace",
  "navList": ["About", "Skills", "Projects", "Blog", "Contact"],
  "about": {
    "fname": "Sachin",
    "lname": "Rao",
    "occ": "software engineer",
    "primary": "based in Bengaluru. I'm Passionate about building application and learning new technologies. In my spare time I love to play badminton, reading and listening to music.",
    "secondary": ""
  },

  "skills": {
    "skillList": [
      {
        "name": "HTML",
        "image": "https://i.pinimg.com/736x/ca/e1/b4/cae1b4f6b223fe5a7bb712b680cffa67.jpg",
        "exp": 1,
        "add": false
      },
      {
        "name": "CSS",
        "image": "https://i.pinimg.com/736x/75/e4/d6/75e4d6d5a0f6b8f4e4030f9b00511ca7.jpg",
        "exp": 1,
        "add": false
      },
      {
        "name": "JS",
        "image": "https://i.pinimg.com/736x/af/1f/b4/af1fb4e8700c6aa2c5b8d3e915eb6e99.jpg",
        "exp": 1,
        "add": true
      },
      {
        "name": "React",
        "image": "https://i.pinimg.com/736x/3f/26/40/3f2640efdb2a1805ebbdef5e3d373937.jpg",
        "exp": 1,
        "add": true
      },

      {
        "name": "C++",
        "image": "https://i.pinimg.com/236x/ff/03/e2/ff03e272b99f9aa0b467289a98b63084.jpg",
        "exp": 1,
        "add": true
      },
      {
        "name": "Python",
        "image": "https://i.pinimg.com/736x/82/a2/18/82a2188c985ce75402ae44fc43fe7e5e.jpg",
        "exp": 1,
        "add": true
      },
      {
        "name": "MongoDb",
        "image": "https://i.pinimg.com/236x/e8/ab/b4/e8abb49f605c7f61553c8268ef0a56aa.jpg",
        "exp": 1,
        "add": true
      },
      {
        "name": "Angular",
        "image": "https://i.pinimg.com/236x/e6/f3/20/e6f3204bd34862cd764314637857e193.jpg",
        "exp": 1,
        "add": true
      },

      {
        "name": "GIT",
        "image": "https://i.pinimg.com/736x/a9/5a/ad/a95aadde4325065401dc6942ea5dad90.jpg",
        "exp": 1,
        "add": true
      }
    ]
  },

  "projects": [
    {
      "name": "QuizWhiz",
      "description": "The Interactive Quiz Application is designed to provide an engaging and challenging quiz experience. The capabilities of a Restful API and the Axios library, this application dynamically fetches quiz data to offer a seamless and diverse set of questions.The application can incorporate a scoring system to track users' progress",
      "image": "https://i.pinimg.com/736x/43/85/4d/43854d48702c71afa673b160aadddfde.jpg",
      "link": "",
      "githublink": "https://github.com/sachinaralapura/React-quiz.git",
      "skills": ["React", "GIT", "HTML", "CSS", "JS"]
    },
    {
      "name": "ToDone",
      "description": "The application provides a streamlined interface for creating, organizing, and tracking tasks. To ensure data security and privacy, the application have user authentication using JWT. A MongoDB used to store user information and task data.",
      "image": "https://i.pinimg.com/736x/00/11/9b/00119bff7b33010bd5ccbea97aa2d36a.jpg",
      "link": "",
      "githublink": "https://github.com/sachinaralapura/TODO.git"
    },
    {
      "name": "Expenzo",
      "description": "The Financial Management System is a comprehensive application designed to empower individuals with effective financial tracking and management tools. This project offers users the ability to manage their expenses, monitor accounts, and gain control over their financial well-being.",
      "image": "https://i.pinimg.com/236x/0b/35/09/0b350904e322e07965177e321a148889.jpg",
      "link": "",
      "githublink": "https://github.com/sachinaralapura/Financial-management-system.git"
    },
    {
      "name": "NovelNest",
      "description": "The BookStore MERN Application is a modern and user-friendly platform for managing and exploring a collection of books. Built using the powerful MERN stack (MongoDB, Express, React, and Node.js), this application provides a seamless experience for both administrators and users.",
      "image": "https://i.pinimg.com/236x/74/bf/8b/74bf8b39f26e126c2ed12c86f6a2067a.jpg",
      "link": "",
      "githublink": "git@github.com:sachinaralapura/NovelNest.git"
    },
    {
      "name": "Calculator",
      "description": "This is a fully functional calculator built using HTML, CSS, and JavaScript, designed with a sleek and modern interface. The calculator allows users to perform a wide range of basic and advanced mathematical operations with ease.",
      "image": "https://i.pinimg.com/236x/72/7d/58/727d58554ce1c37412914d14c7951ad0.jpg",
      "link": "https://sachinaralapura.github.io/WSA/Projects/Calculator/level2/",
      "githublink": "https://github.com/sachinaralapura/WSA/tree/main/Projects/Calculator/level2"
    },
    {
      "name": "Image carousel",
      "description": "The Image Carousel Application is an elegant and interactive component built using HTML, CSS, and JavaScript. It allows users to browse through a collection of images with smooth transitions and intuitive controls. This project is perfect for showcasing visual content like photo galleries, product displays, or featured images.",
      "image": "https://i.pinimg.com/236x/da/1d/b1/da1db1452129ce8557f08c8983403752.jpg",
      "link": "https://sachinaralapura.github.io/WSA/Projects/image_slider/level2/",
      "githublink": "https://github.com/sachinaralapura/WSA/tree/main/Projects/image_slider/level2"
    }
  ],

  "contact": {
    "emailJs": {
      "gmailId": "sachin.aralapura@gmail.com",
      "serviceId": "service_fhnjps9",
      "templateId": "template_zak3pv7",
      "publicAPI": "ozlepfS3S0GiQqfQJ"
    },

    "social": [
      {
        "platform": "LinkedIn",
        "link": "",
        "img": "",
        "add": true
      },
      {
        "platform": "GitHub",
        "link": "",
        "img": "",
        "add": true
      },
      {
        "platform": "HackerRank",
        "link": "",
        "img": "",
        "add": true
      },
      {
        "platform": "𝕏",
        "link": "",
        "img": "",
        "add": true
      }
    ]
  }
}
